### ISSUE TITLE
WebUI无法正确显示出文件，只能显示文件夹

### ISSUE THREAD

**Issue by InterestingFred** [BililiveRecorder/BililiveRecorder-WebUI#17]
如图
![图片](https://user-images.githubusercontent.com/106480847/176989525-b22f6d69-d53a-4357-81c4-9cc69584e008.png)

**Comment by shugen002** [comment]
fixed in https://github.com/BililiveRecorder/BililiveRecorder-WebUI/commit/fb0d26c6fb01e82b6dba9ebaaa91d566dec94af5
