### ISSUE TITLE
写一个单文件开箱即用的 webui server

### ISSUE THREAD

**Issue by Genteure** [BililiveRecorder/BililiveRecorder-WebUI#18]
考虑可以用 go 来写，编译成一个可执行文件。

主要考虑有：

- webui.rec.danmuji.org 是 HTTPS 的，无法访问局域网内的 HTTP 服务。
- 手动使用 Nginx Caddy 等部署，操作步数略多，需要编写配置文件，尤其是因为 WebUI 是 SPA 项目。
- 用户自行部署更方便控制使用的具体版本，方便与使用的录播姬同步。

**Comment by shugen002** [comment]
目前我最新的想法是拿个electron之类的玩意，把cli和webui一包
