### ISSUE TITLE
WebUI的文件显示出现乱序

### ISSUE THREAD

**Issue by InterestingFred** [BililiveRecorder/BililiveRecorder-WebUI#22]
如图

![图片](https://user-images.githubusercontent.com/106480847/178505811-5fe8c839-4414-4177-8599-f9664fd7ae6d.png)

希望可以按照文件名称或修改时间排序

备注：使用的版本：
brec:2.1.1
webui:2.1.3（嵌入版本）

**Comment by shugen002** [comment]
done.
