### ISSUE TITLE
webui在白色界面的时候不显示房间号

### ISSUE THREAD

**Issue by Arukassss** [BililiveRecorder/BililiveRecorder-WebUI#24]
![E`(E1ZS$TQ~8K3(D8~ O}R8](https://user-images.githubusercontent.com/89686441/183452934-bb850c56-f95e-4c6a-83d5-941b060ae769.png)

**Comment by shugen002** [comment]
fixed in e7783c4d1973e6b699b62a8593c8801a29bd8d45
