### ISSUE TITLE
WebUI的文件管理器界面增加【删除】文件的按钮

### ISSUE THREAD

**Issue by lrtstm** [BililiveRecorder/BililiveRecorder-WebUI#26]
由于不是所有录制的直播录像都是需要的，所以需要有所删除，故希望在WebUI的文件管理器界面增加【删除】文件的按钮，方便把不重要的一些录像删除，腾出存储空间。

**Comment by shugen002** [comment]
录播姬本身并未提供删除接口，只提供了简单的列出文件和下载文件功能，所以暂时无法去做这个删除。
cc @Genteure
