### ISSUE TITLE
支持部署在子路径

### ISSUE THREAD

**Issue by chirsz-ever** [BililiveRecorder/BililiveRecorder-WebUI#29]
有两个方案

1. 配置 `base = './'` 并使用 `createWebHashHistory` 来路由，好处是能默认生效，无需用户太多操作，坏处是 break change。
2. #28，需要部署在子路径的用户要手动生成网站并上传到服务器的 `wwwroot/ui` 目录。

如果使用方案 1，仍需要修改 request api 部分代码来适配子路径。

如果使用方案 2，有一个改进建议：假定 Embedded-WebUI 始终在命令行软件 HTTP 服务的 `/ui` 路径下，这样 `BASE_URL` 可以只写反向代理的路径，如 `/brec/`，request api 部分代码也不用找 `BASE_URL` 的父路径。

**Comment by Genteure** [comment]
以前讨论过用 `createWebHashHistory`，shugen 最终决定用 `createWebHistory`，看看他的意见。
目前文件浏览器已经在用 hash 作为文件的路径了，如果要修改的话需要考虑一下。

如果有必要的话可以在 ASP.NET Core 层面对返回的 HTML 做动态修改，类似现在的 [`index.html`](https://github.com/BililiveRecorder/BililiveRecorder/blob/e2bd7becb0ccba125854cb61d3fc05e69f265d3a/BililiveRecorder.Web/embeded/index.html) 一样。
可以注入一个 js 变量或者 `<meta>` 标签，写入服务器视角当前请求的路径，在前端用实际完整路径减去这个路径就可以得到反代的根路径了。

例子：

```js
const SERVER_PATH = '/ui/recorder/local/rooms';

if (location.pathname.endsWith(SERVER_PATH)) {
    var i = location.pathname.indexOf(SERVER_PATH);
    if (i > -1) {
        console.log(location.pathname.slice(0, i));
    }
}
```

**Comment by shugen002** [comment]
我在做tray的时候有打算加入服务器动态修改，用来把一部分的信息提前输入到页面中去。。。

然后createWebHashHistory不是没想过，只是感觉不舒服，现在文件浏览器那边已经用了hash就更不可能切换了过去了。

然后 #28 这样光加baseurl是不行的，你还得去处理html中对css和js的引用，或者你在网站服务器上添加多一条 try_file 规则，不然还是裂开。

我还没有想法去深度研究vite的逻辑，如果你有能力修改这个css和js的加载的话，我这边欢迎PR

**Comment by chirsz-ever** [comment]
所以一般只有方案 1 使用 Hash 历史模式才能配置 `base = './'`。

#28 支持的是方案 2 说的“用户要手动生成网站”，指要执行一遍 `BASE_URL=/brec/ui/ VITE_EMBEDDED_BUILD=true npx vite build` 再把生成的网站复制到服务器 `wwwroot/ui` 下。

如果可以改服务端，那完全可以加一个 `--base` 命令行参数来控制生成 [base 标签](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base)，比如 `--base=/brec` 会插入 `<base href="/brec/ui/" />`，然后如果以 `base='./'` 参数生成网站，不论实际访问路径如何，用相对路径加载 js 和 css 的结果都会保持正确。

JavaScript 中的相对路径解析也是跟随 `base` 标签的（至少 `fetch` 是这样），所以 request api 只需要在开头加上 '../'，改为请求 `../api/xxx` 即可。

**Comment by Genteure** [comment]
加一个 `<base>` 也可以。

动态计算的好处是随便放到哪个路径都能跑，不需要手动修改启动参数。

页面加载的时候用 js 加一个 `<base>` 也是可以的吧？

**Comment by shugen002** [comment]
我先确认下是否可行

**Comment by chirsz-ever** [comment]
> 页面加载的时候用 js 加一个 `<base>` 也是可以的吧？

https://stackoverflow.com/questions/20308395/how-to-dynamically-set-the-base-tag 好像还真行。

那就是服务器在 HTML 里插入类似
```
<script>
var brec_ui_request_path = '/brec/ui/';
</script>
```

然后安排一段脚本删除 `location.pathname` 后缀，构造并插入一个 `<base>`。

**Comment by shugen002** [comment]
我测试了一下，我直接在html中写入了
```
<base href="/bala/">
```
发现了以下问题：
- [x] 路由炸了 (已解决
- [ ] 设置页右侧的快速跳转导航

**Comment by shugen002** [comment]
> 加一个 `<base>` 也可以。
> 
> 动态计算的好处是随便放到哪个路径都能跑，不需要手动修改启动参数。
> 
> 页面加载的时候用 js 加一个 `<base>` 也是可以的吧？

你必须在其他js和css前面加上base元素才有效

**Comment by Genteure** [comment]
我在两个仓库的 `feature/dynamic-webui-base` 分支上实现了服务器注入请求路径、前端计算 SPA 的根路径。

- https://github.com/BililiveRecorder/BililiveRecorder/tree/feature/dynamic-webui-base
- https://github.com/BililiveRecorder/BililiveRecorder-WebUI/tree/feature/dynamic-webui-base

测试：

直接访问以下所有地址都能正确得出 `/ui/`

- `http://127.0.0.1:2356/ui`
- `http://127.0.0.1:2356/ui/`
- `http://127.0.0.1:2356/ui/recorder/local`

使用 Caddy 反代：

```caddyfile
http://localhost:2357

route /test/proxy/brec/* {
	uri strip_prefix /test/proxy/brec
	reverse_proxy localhost:2356
}

respond "caddy here"
```

然后访问

- `http://localhost:2357/test/proxy/brec/ui`
- `http://localhost:2357/test/proxy/brec/ui/`
- `http://localhost:2357/test/proxy/brec/ui/aaaaaaa`

都能正确得出 `/test/proxy/brec/ui/`

```
SERVER_PATH: /aaaaaaa
location.pathname: /test/proxy/brec/ui/aaaaaaa
base path: /test/proxy/brec/ui/
```

![image](https://user-images.githubusercontent.com/11240579/186890074-5f8911db-938c-4e6f-b1e2-27355794de7d.png)

**Comment by Genteure** [comment]
push 了更新了一下，倒是能用，但是我测试 chrome 会先尝试以 base 为 `/` 加载 js 和 css，然后 base 更新之后再重新加载

![image](https://user-images.githubusercontent.com/11240579/186903031-8f3c9f2e-e4c6-40bc-9b41-4b884226a5a0.png)

**Comment by Genteure** [comment]
反代之后也能用，但也有一样会先加载一次 `/assets/index.xxxx.js` 的问题。
有啥思路吗？

![image](https://user-images.githubusercontent.com/11240579/186904377-b59ef013-3a6f-48df-b8d1-4cc31a52e437.png)

**Comment by Genteure** [comment]
在录播姬里改了 WebUI 的 HTML 延迟加载 css 和 js，解决了上面的加载两次的问题，修改过的 HTML 效果：

![image](https://user-images.githubusercontent.com/11240579/186947882-be41a21b-ca92-4a31-867d-536f8e7f48a7.png)
![image](https://user-images.githubusercontent.com/11240579/186948606-77362f73-30af-44a1-8c0a-29f69703f27e.png)


已经 push 到 `BililiveRecorder` 的 `feature/dynamic-webui-base` 分支。

**Comment by Genteure** [comment]
已合并到主分支
