### ISSUE TITLE
部署在子路径时会出现一些问题

### ISSUE THREAD

**Issue by chirsz-ever** [BililiveRecorder/BililiveRecorder-WebUI#32]
我用命令行工具内置的 2.3.0 版，在 2.3.1 版里应该也能复现。

假设部署到 `https://hello.xyz/brec/` 路径下。

- [x] `https://hello.xyz/brec/ui/recorder/local/files` 界面下文件夹的目标 URL 正确，文件链接依然是相对网站根路径的 `https://hello.xyz/file/xxxx`；
- [x] `https://hello.xyz/brec/file/` 界面中点击“播放”时跳转的播放器页面链接是相对于根路径的 `https://hello.xyz/player/#/xxxx`；
- [x] 从 `/ui/` 的子路径如 `https://hello.xyz/brec/ui/recorder/local` 访问 WebUI 会出错。

**Comment by Genteure** [comment]
> 从 /ui/ 的子路径如 https://hello.xyz/brec/ui/recorder/local 访问 WebUI 会出错。

具体的错误是什么？
控制台输出之类

**Comment by chirsz-ever** [comment]
> 具体的错误是什么？

加载 https://hello.xyz/ui/assets/index.ae8a3a08.js 失败。

**Comment by Genteure** [comment]
html 里面应该有一个 `<script data-href="/recorder/local">` 你看一下你访问的时候实际是什么

**Comment by chirsz-ever** [comment]
> html 里面应该有一个 `<script data-href="/recorder/local">` 你看一下你访问的时候实际是什么

返回的 HTML （经过格式化）

```html
<!DOCTYPE html>
<html lang="zh">
<meta charset="UTF-8">
<base href="/">
<link rel="icon" href="/ui/favicon.ico">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>BililiveRecorder-WebUI</title>
<template id="delayed-init">
    <script type="module" crossorigin="" src="/ui/assets/index.ae8a3a08.js"></script>
    <link rel="stylesheet" href="/ui/assets/index.3af92e3a.css">
</template>
<script data-href="/recorder/local">
    (function () {
        const n = document.currentScript;
        if (n && "string" == typeof n.dataset.href) {
            const u = n.dataset.href, f = document.getElementsByTagName("base")[0], i = location.pathname, r = console.log;
            if (r("SERVER_PATH: " + u), r("location.pathname: " + i), u.length === 0) {
                let n = i + "/";
                f.href = n; r("base path: " + n)
            } else if (i.endsWith(u)) {
                var t = i.lastIndexOf(u);
                if (t > -1) {
                    let n = i.slice(0, t) + "/";
                    f.href = n;
                    r("base path: " + n)
                }
            } else
                r("????")
        }
        const i = document.getElementById("delayed-init");
        document.head.append(i.content.cloneNode(!0));
        i.remove();
        n.remove()
    })()
</script>
<div id="app"></div>

</html>
```

**Comment by shugen002** [comment]
插进去的代码不是我写的，绝不背锅（蛤

**Comment by shugen002** [comment]
https://github.com/BililiveRecorder/BililiveRecorder/blob/dev/webui/build.sh#L5
看了下，是主程序构建脚本没有及时更新导致的问题，我已经过去改了

**Comment by Genteure** [comment]
console 输出是啥？没看出来哪里有问题。

**Comment by Genteure** [comment]
新版本再鸽会，`ghcr.io/bililiverecorder/bililiverecorder:dev` 已经解决了第 3 个问题

**Comment by Genteure** [comment]
第二条在 https://github.com/BililiveRecorder/BililiveRecorder/commit/cdd563a7531d8afee79bac96c435560fafd0839e 里解决了

**Comment by shugen002** [comment]
第一条应该也解决了，虽然有点暴力

**Comment by Genteure** [comment]
发了新版本了
