### ISSUE TITLE
希望WebUI给 房间列表-->添加房间 加个【Ctrl+Enter】键快捷添加录制房间

### ISSUE THREAD

**Issue by komori-flag** [BililiveRecorder/BililiveRecorder-WebUI#36]
![image](https://user-images.githubusercontent.com/105255344/194472551-ac0005a4-e488-4076-9e4b-49017ec06f83.png)

**Comment by shugen002** [comment]
问一下 这个ctrl+enter之后的表现应该是关闭弹窗还是保留弹窗

**Comment by Genteure** [comment]
我觉得关闭比较好。
因为房间号文本框已经支持一次添加多个直播间了，不应该会有连续多次输入房间信息、添加房间的需求。

**Comment by komori-flag** [comment]
我觉得关闭弹窗会比较好，跟点击“添加”按钮同样。
因为对于一般用户来说，点击“添加”按钮的情形通常是已经填写好需要添加的房间信息之后，而且房间号的文本框也支持添加多个直播间信息，故此触发提交后应该直接关闭弹窗会更好。
