### ISSUE TITLE
WebUI群控版2.5.1-master.2-g73f2fdd3无法读取日志

### ISSUE THREAD

**Issue by ItsukaRilu** [BililiveRecorder/BililiveRecorder-WebUI#37]
@shugen002 
如题，之前版本（就是那个2.4.x然后实际上是2.5的版本）还是可以正常访问日志的，重新拉镜像更新webui群控版之后就不行了。
## 如图，直接访问录播姬webui是可以正常显示日志的。
![image](https://user-images.githubusercontent.com/77743653/198039033-48edfb67-f8c7-4c69-ab43-64debd3d98a8.png)

## 附检查元素截图
![image](https://user-images.githubusercontent.com/77743653/198039646-86736fc3-3bbf-4009-9bf4-38ee146a2cd5.png)
![image](https://user-images.githubusercontent.com/77743653/198040290-5681b06b-f611-4687-a3f7-4bab65916919.png)
![image](https://user-images.githubusercontent.com/77743653/198040033-d5636fdf-1e55-437d-a904-69bab4c07200.png)

## 去除[ ?after= ]参数后的请求
![image](https://user-images.githubusercontent.com/77743653/198044993-dd46caf4-ea7c-4beb-b2ed-dd78e892aef2.png)

**Comment by ItsukaRilu** [comment]
master-f12cb02修了
好快的修（

**Comment by shugen002** [comment]
fixed in https://github.com/BililiveRecorder/BililiveRecorder-WebUI/commit/f12cb022fc73397a54189de43c64707dcbe0c1a6
