### ISSUE TITLE
详细信息中的总时长存在歧义

### ISSUE THREAD

**Issue by 6Bpencle** [BililiveRecorder/BililiveRecorder-WebUI#39]
![W4J7L(H`QZ5DSP(E9VU7G 4](https://user-images.githubusercontent.com/31346958/198846515-d01b5248-9236-46ea-b96b-503a2c229b11.png)
会话时长对应是完整录制时长，总时长对应是当前片段时长

**Comment by shugen002** [comment]
稍微翻了下，这个总时长的来源是：

https://github.com/BililiveRecorder/BililiveRecorder/blob/bb8e23ab4de9776a7e4d3f02ae6062e4dafe46ae/BililiveRecorder.Web/Models/Rest/RoomRecordingStatsDto.cs#L30-L33

所以这个总时长是可以改回：`当前文件的最大时间戳`
当对于会话时长这个实际并不对于完整录制时长。
