### ISSUE TITLE
Web UI 新增直播状态排序

### ISSUE THREAD

**Issue by oxygenkun** [BililiveRecorder/BililiveRecorder-WebUI#46]
### Problem

有一类场景是，我已经将一些房间添加到预选列表中，但是自动录制状态关闭。我可以通过直播状态排序优先看到正在直播的房间并手动开启录制。

### Proposal

Web UI 新增直播状态排序。

**Comment by shugen002** [comment]
emmm是个好主意，但我觉得或许应该合并到录制状态去，改成叫录制状态优先排序 顺序按照录制中、直播中但未录制、未直播已开启自动录制、未直播未开启自动录制，然后这四类里面再按照房间号排序？但这样弄叫录制状态优先排序好怪，希望能有更好的建议

**Comment by oxygenkun** [comment]
我觉得保留“录制状态”名字也没问题，或者说叫“录制状态&直播状态”排序

**Comment by shugen002** [comment]
我在反馈讨论群那边从gen佬口中得到了一个我目前最满意的答案：
> 记录最后选的排序顺序
> 最终效果比如先选了房间号排序，然后切换成录制状态排序，排序就先按录制状态排序（因为是当前选择的排序方式）状态一样的再按房间号排序（因为是上次选择的）
伪代码
> 
> 切换排序方式
> 
> 当前排序方式 = “房间号”
> 历史排序方式 = ［］
> 
> 历史排序方式.removeItem（当前排序方式） //从历史中移除，历史不只增不减，一种排序方式只出现一次
> 历史排序方式.push（当前排序方式）//放到最新一个
> 
> 然后排序的时候
> 
> foreach（var 排 in 历史排序方式.revrrse（））
> 房间列表 = 房间列表.sort（排）

**Comment by oxygenkun** [comment]
查了一下js的sort，好像按照ecma的要求需要是稳定的。那在排序后同优先级的情况下就保持之前的顺序，不用考虑更复杂的方式。

**Comment by oxygenkun** [comment]
commit 7ab04fccbec49983b4dff043ee7c1d1746246d6d

在点击直播状态后关闭窗口再进入，虽然下拉显示直播排序，但是实际没有排序。

**Comment by shugen002** [comment]
https://github.com/BililiveRecorder/BililiveRecorder-WebUI/actions/runs/5135365405 修了

**Comment by oxygenkun** [comment]
looks good! THX

**Comment by shugen002** [comment]
没啥问题的话，把pr和issue关了吧
