### ISSUE TITLE
设置页面保存按钮改成浮动在界面最上方

### ISSUE THREAD

**Issue by Genteure** [BililiveRecorder/BililiveRecorder-WebUI#50]
经常有人修改设置后没点保存按钮，感觉主要原因是页面滚动之后看不见保存按钮，就默认成实时提交了。
解决方法：把设置页面保存按钮改成浮动在显示区域上方，而不是跟随页面内容一起滚动。

**Comment by shugen002** [comment]
111111
直接给你单拉一条弄成discord那种如何？
