### ISSUE TITLE
问一下为什么我的弹幕录制总是隔一段时间录一次

### ISSUE THREAD

**Issue by czhko** [BililiveRecorder/BililiveRecorder-WebUI#59]
![QQ截图20231209132711](https://github.com/BililiveRecorder/BililiveRecorder-WebUI/assets/54000959/f912f04d-ba7c-4fbc-9bfe-a954a4776c46)
就像这张截图里显示的一样，第一次在22秒录制几个后，第二次就在1分钟才开始录几个
请问是改了什么参数吗，要怎么改回去呢

**Comment by Genteure** [comment]
9月份的时候B站加了检测和风控，第三方工具连接弹幕服务器被检测出来之后就会给脏数据，没有解决办法。
