### ISSUE TITLE
 启动录制出错：System.Exception: no supported stream url, qn: 10000

### ISSUE THREAD

**Issue by miRemid** [BililiveRecorder/BililiveRecorder-WebUI#60]
2023-12-09T15:17:25.3643410Z

启动录制出错

Warning

System.Exception: no supported stream url, qn: 10000 at BililiveRecorder.Core.Recording.RecordTaskBase.FetchStreamUrlAsync(Int32 roomid) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Recording/RecordTaskBase.cs:line 247 at BililiveRecorder.Core.Recording.RecordTaskBase.StartAsync() in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Recording/RecordTaskBase.cs:line 137 at BililiveRecorder.Core.Room.<>c__DisplayClass100_0.<<CreateAndStartNewRecordTask>b__0>d.MoveNext() in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Room.cs:line 304
RoomId
*****
SourceContext
BililiveRecorder.Core.Room
ProcessId
1
ThreadId
14
ThreadName
.NET ThreadPool Worker
ActionId
029a40c0-2d2c-4672-b586-efc8102d58e7
ActionName
BililiveRecorder.Web.Api.RoomController.CreateRoom (BililiveRecorder.Web)
RequestId
0HMVOIDQ4ITSS:00000007
RequestPath
/api/room/
ConnectionId
0HMVOIDQ4ITSS
ExceptionDetail
{"Type":"System.Exception","HResult":-2146233088,"Message":"no supported stream url, qn: 10000","Source":"BililiveRecorder.Core","TargetSite":"Void MoveNext()"}

**Comment by miRemid** [comment]
刚启动的时候还能录制，过了一段时间后就不能录制了，Docker部署

**Comment by shugen002** [comment]
常见问题1：录制画质低、画面模糊：B站故意的，不登录不给高画质。就像在浏览器里退出登录/隐身标签页打开B站看直播的效果一样。解决方法：加cookie、看精华消息最新一条。

完全无关的另一个常见问题2：无法录制部分分区的直播，基本都是多人联机游戏的分区。B站为了防炸弹人对部分分区有特殊处理，强制打码、强制直播延迟、没有FLV只有HLS格式的直播流、海外无法观看直播等。录播姬现在只支持 FLV 不支持 HLS 所以这些分区的直播录不了。

**Comment by shugen002** [comment]
忘说了，这类问题，请在 https://github.com/BililiveRecorder/BililiveRecorder 这边反馈
