### ISSUE TITLE
设置界面勾选使用默认值后不弹出保存弹窗

### ISSUE THREAD

**Issue by Kylineyes** [BililiveRecorder/BililiveRecorder-WebUI#63]
WebUI v2.10.2
设置的值已经被自动修改成了默认的值，但是没有保存的弹窗出现，无法进行保存。

**Comment by shugen002** [comment]
保存按钮在顶部，没有弹窗。。。

**Comment by Kylineyes** [comment]
![image](https://github.com/BililiveRecorder/BililiveRecorder-WebUI/assets/23229665/a29326ad-f623-4dc5-a5df-ad0ee63fd676)
应该指的是红框这一块吧，在我这里浏览器（edge 123.0.2420.53）是锚定底部出现的弹窗。

当我点击了「HTTP API 检查时间间隔」的「使用默认值」勾选框后，并不会弹出红框。

**Comment by shugen002** [comment]
欸，我忘了总计做了这个了，，，，
这个问题，我晚点有空看看，应该是哪里我没处理好。。
