### ISSUE TITLE
录制无法指定画质，默认最低画质

### ISSUE THREAD

**Issue by Max66888** [BililiveRecorder/BililiveRecorder-WebUI#64]
群辉DSM7.1 Docker运行
录制无法指定画质，默认最低画质
![Snipaste_2024-03-28_19-22-24](https://github.com/BililiveRecorder/BililiveRecorder-WebUI/assets/101586089/be016b3a-3e7f-450b-897d-83951690c79e)

**Comment by shugen002** [comment]
高级设置里可以填 Cookie https://rec.danmuji.org/user/settings/
